# Generated by Django 5.2.17 on 2026-09-16 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('register_number', models.CharField(help_text='Unique college registration/roll number', max_length=30, unique=True)),
                ('email', models.EmailField(help_text='Valid email address of the student', max_length=100)),
                ('department', models.CharField(help_text='Department of study (e.g., Computer Science, Mechanical, etc.)', max_length=100)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], help_text='Academic year of study', max_length=20)),
                ('phone', models.CharField(help_text='10-digit contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits without country code or spaces.', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the student record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the student record was last updated')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-id'],
            },
        ),
    ]
